//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SharpMT.Properties.Resources.get_ResourceManager():System.Resources.ResourceManag" +
    "er")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SharpMT.Properties.Resources.get_Culture():System.Globalization.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SharpMT.Properties.Resources.set_Culture(System.Globalization.CultureInfo):Void")]

namespace SharpMT.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpMT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap addLink {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("addLink", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap advancedMode {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("advancedMode", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap ApplicationIcon {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ApplicationIcon", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap blogLinks {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("blogLinks", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap bold {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("bold", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("copy", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap customTags {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("customTags", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("cut", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("delete", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap edit {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("edit", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap find {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("find", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap go {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("go", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap home {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("home", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap italics {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("italics", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap music {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("music", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap newDraft {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("newDraft", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap openDraft {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("openDraft", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap options {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("options", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("paste", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap plugin {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("plugin", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap post {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("post", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap posted {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("posted", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap preview {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("preview", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap saveDraft {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("saveDraft", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap spellCheck {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("spellCheck", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap splash {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("splash", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Icon TracingApp {
            get {
                return ((System.Drawing.Icon)(ResourceManager.GetObject("TracingApp", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap underline {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("underline", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap updateCategories {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("updateCategories", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap updateLinks {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("updateLinks", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap updateTextFilters {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("updateTextFilters", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap uploadImage {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("uploadImage", resourceCulture)));
            }
        }
    }
}
